package dk.dtu.compute.se.pisd.roborally.model;

public enum ActionField {
    CONVEYOR_BELT,
    RIGHT_CONVEYOR_BELT,
    LEFT_CONVEYOR_BELT,

    DOUBLE_CONVEYOR_BELT,
    DOUBLE_RIGHT_CONVEYOR_BELT,
    DOUBLE_LEFT_CONVEYOR_BELT,
    DOUBLE_LEFTTREE_CONVEYOR_BELT,
    DOUBLE_RIGHTTREE_CONVEYOR_BELT,

    LEFT_GEAR,
    RIGHT_GEAR,

    BOARD_LASER_START,
    BOARD_LASER,
    BOARD_LASER_END,

    PIT,
    PUSH_PANEL,
    STARTING_GEAR,
    ENERGY_SPACE,
    CHECKPOINT,
    WALL,
    PRIORITY_ANTENNA,
    RESPAWN,
    NORMAL
}
